#판다스

In [57]:
import pandas as pd

In [58]:
#데이터프레임 - 2차원 
df=pd.DataFrame({'날짜':['2000-01-01','2000-01-02','2000-01-03'],
                 '지점':[108, 108, 108],
                 '평균기온':[13.5, 16.2, 16.2],
                 '최저기온':[7.9, 7.9, 13.1],       
                 '최고기온':[20.7, 22, 21.3]})

In [3]:
df

날짜   지점  평균기온  최저기온  최고기온
0  2000-01-01  108  13.5   7.9  20.7
1  2000-01-02  108  16.2   7.9  22.0
2  2000-01-03  108  16.2  13.1  21.3

In [4]:
#데이터프레임 - 리스트, index, column 설정

In [59]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], index = ['a','b','c'], columns = ['c0','c1','c2'])
df

c0  c1  c2
a   1   2   3
b   4   5   6
c   7   8   9

In [18]:
#인덱스 확인하기

In [19]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [8]:
#컬럼 확인하기

In [9]:
df.columns

Index(['c0', 'c1', 'c2'], dtype='object')

In [10]:
#행 인덱스 변경

In [20]:
df.index=['0번','1번','2번']
df.columns=['n0','n1','n2']

In [21]:
df

n0  n1  n2
0번   1   2   3
1번   4   5   6
2번   7   8   9

In [22]:
#행/열 삭제

In [23]:
df1=df.drop('0번',axis=0) #axis=0생략가능
df1

n0  n1  n2
1번   4   5   6
2번   7   8   9

In [28]:
df2=df.drop('n0',axis=1) # 0은 세로 1은 세로를 삭제
df2

n1  n2
0번   2   3
1번   5   6
2번   8   9

In [26]:
df3=df.drop(['0번','2번'],axis=0) #axis=0생략가능
df3

n0  n1  n2
1번   4   5   6

In [29]:
df4=df.drop(['n0','n2'],axis=1)
df4

n1
0번   2
1번   5
2번   8

In [ ]:
#기존의 값을 변경할 때, 원본 데이터를 수정하는 inplace = True 옵션을 사용하여 변경
#기존 데이터는 두고, 새로운 데이터에 저장할 때에는 명령어 앞에 df1= 처럼 원하는 이름으로 새로운 객체를 만듦

In [ ]:
df.drop(['n0','n2'],axis=1, inplace = True)
df

In [ ]:
#df 변경하기!

In [80]:
import pandas as pd
exam_data={'수학':[90,80,70],'영어':[98,85,95],'음악':[85,95,100],'체육':[100,90,90]}
df = pd.DataFrame(exam_data, index = ['서준','우현','인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  85   95   90
인아  70  95  100   90

In [81]:
#column 추가하기

In [82]:
df['국어']= 80
df

수학  영어   음악   체육  국어
서준  90  98   85  100  80
우현  80  85   95   90  80
인아  70  95  100   90  80

In [83]:
#column값 변경하기

In [84]:
df['국어']=[100,100,80]
df

수학  영어   음악   체육   국어
서준  90  98   85  100  100
우현  80  85   95   90  100
인아  70  95  100   90   80

In [85]:
#행 추가하기

In [86]:
df.loc['수민']= 80
df

수학  영어   음악   체육   국어
서준  90  98   85  100  100
우현  80  85   95   90  100
인아  70  95  100   90   80
수민  80  80   80   80   80

In [87]:
#행 변경하기

In [88]:
df.loc['수민']=[80,70,90,100,10]
df

수학  영어   음악   체육   국어
서준  90  98   85  100  100
우현  80  85   95   90  100
인아  70  95  100   90   80
수민  80  70   90  100   10

In [89]:
#원소 값 변경

In [90]:
df.loc['서준','영어']=1
df

수학  영어   음악   체육   국어
서준  90   1   85  100  100
우현  80  85   95   90  100
인아  70  95  100   90   80
수민  80  70   90  100   10

In [91]:
#행,열 위치 바꾸기(전치)

In [92]:
df=df.T

In [93]:
df

서준   우현   인아   수민
수학   90   80   70   80
영어    1   85   95   70
음악   85   95  100   90
체육  100   90   90  100
국어  100  100   80   10

In [94]:
#제자리로
df=df.T

In [95]:
df

수학  영어   음악   체육   국어
서준  90   1   85  100  100
우현  80  85   95   90  100
인아  70  95  100   90   80
수민  80  70   90  100   10

In [96]:
#인덱스 기준 정렬

In [97]:
df1=df.sort_index()
df1

수학  영어   음악   체육   국어
서준  90   1   85  100  100
수민  80  70   90  100   10
우현  80  85   95   90  100
인아  70  95  100   90   80

In [98]:
#특정 열 기준 정렬

In [99]:
df2=df.sort_values(by='영어',ascending=True) #ascending : 오름차순 속성
df2

수학  영어   음악   체육   국어
서준  90   1   85  100  100
수민  80  70   90  100   10
우현  80  85   95   90  100
인아  70  95  100   90   80

In [100]:
#df의 평균값 구하기

In [101]:
df.mean()

수학    80.00
영어    62.75
음악    92.50
체육    95.00
국어    72.50
dtype: float64

In [102]:
#df의 중간값 구하기

In [103]:
df.median()

수학    80.0
영어    77.5
음악    92.5
체육    95.0
국어    90.0
dtype: float64

In [104]:
#df의 상관계수 구하기

In [105]:
df.corr()

수학        영어        음악        체육        국어
수학  1.000000 -0.904453 -0.948683  0.707107  0.191127
영어 -0.904453  1.000000  0.903679 -0.741600 -0.238610
음악 -0.948683  0.903679  1.000000 -0.894427  0.090660
체육  0.707107 -0.741600 -0.894427  1.000000 -0.473016
국어  0.191127 -0.238610  0.090660 -0.473016  1.000000

실습해보기1

In [ ]:
#데이터프레임 - 리스트, index, column 설정

In [62]:
import pandas as pd
jj = pd.DataFrame([[20,25,30],[10,10,5],[5,10,15]], index = ['당근판매량','귤판매량','무판매량'], columns = ['9/24','9/25','9/26'])
jj

9/24  9/25  9/26
당근판매량    20    25    30
귤판매량     10    10     5
무판매량      5    10    15

In [ ]:
#인덱스 확인하기

In [63]:
jj.index

Index(['당근판매량', '귤판매량', '무판매량'], dtype='object')

In [61]:
#컬럼 확인하기

In [64]:
jj.columns

Index(['9/24', '9/25', '9/26'], dtype='object')

In [ ]:
#인덱스, 컬럼 변경
#인덱스 :['당근','귤','무']변경
#컬럼 : ['09-24','09-25','09-26']변경

In [65]:
jj.T
jj.index = ['당근', '귤', '무']
jj.columns = ['9/1', '13', 'ss']
jj

9/1  13  ss
당근   20  25  30
귤    10  10   5
무     5  10  15

In [ ]:
#'당근'행 삭제 후 jj1저장

In [67]:
jj1 = jj.drop(['당근'], axis = 0)
jj1

9/1  13  ss
귤   10  10   5
무    5  10  15

In [ ]:
#'09-24','09-26' 열 삭제 후 jj2저장

In [73]:
jj2 = jj.drop(['9/1', '13'], axis = 1)
jj2

ss
당근  30
귤    5
무   15

In [ ]:
#jj 다시 불러오기

In [74]:
import pandas as pd
jj = pd.DataFrame([[20,25,30],[10,10,5],[5,10,15]], index = ['당근판매량','귤판매량','무판매량'], columns = ['9/24','9/25','9/26'])
jj

9/24  9/25  9/26
당근판매량    20    25    30
귤판매량     10    10     5
무판매량      5    10    15

In [ ]:
#jj에 '9/22' column 추가하기, 판매량은 [40,3,20]

In [76]:
jj['9/22'] = [40,3,20]
jj

9/24  9/25  9/26  9/22
당근판매량    20    25    30    40
귤판매량     10    10     5     3
무판매량      5    10    15    20

In [ ]:
#'포도판매량' index 추가하기, 판매량은 전체 30

In [106]:
jj.loc['포도판매량'] =30

In [ ]:
#'무판매량' index값 [10,10,15,20]으로 변경하기

In [126]:
jj.loc['무판매량'] = [10, 10, 15, 20, 20]
jj

9/24  9/25  9/26  9/22  무판매량
당근판매량    20    25    30    40    10
귤판매량     10    10     5     3    10
포도판매량    30    25    30    30    20
무판매량     10    10    15    20    20

In [122]:
#'포도판매량','9/25' 원소 값 25로 변경

In [125]:
jj.loc['포도판매량', '9/25'] = 25

In [119]:
#행,열 위치 바꾸기(전치)하여 jj에 저장

In [127]:
jj.drop(['무판매량'], axis = 1, inplace = True)

In [128]:
jj

9/24  9/25  9/26  9/22
당근판매량    20    25    30    40
귤판매량     10    10     5     3
포도판매량    30    25    30    30
무판매량     10    10    15    20

In [ ]:
#인덱스 기준 오름차순 정렬하고 jj1에 저장

In [142]:
jj1=jj.sort_values(by='9/22',ascending=False)
jj1

9/24  9/25  9/26  9/22
당근판매량    20    25    30    40
포도판매량    30    25    30    30
무판매량     10    10    15    20
귤판매량     10    10     5     3

In [ ]:
#'당근판매량' 컬럼 기준 오름차순 정렬후 jj2에 저장

In [136]:
jj.sort_index()

9/24  9/25  9/26  9/22
귤판매량     10    10     5     3
당근판매량    20    25    30    40
무판매량     10    10    15    20
포도판매량    30    25    30    30

In [ ]:
#jj의 평균값 구하기

In [134]:
jj.mean()

9/24    17.50
9/25    17.50
9/26    20.00
9/22    23.25
dtype: float64

In [ ]:
#jj의 중간값 구하기

In [141]:
#jj의 상관계수 구하기
jj.median()

9/24    15.0
9/25    17.5
9/26    22.5
9/22    25.0
dtype: float64

In [138]:
jj.corr()

9/24      9/25      9/26      9/22
9/24  1.000000  0.904534  0.852803  0.667531
9/25  0.904534  1.000000  0.942809  0.859964
9/26  0.852803  0.942809  1.000000  0.957413
9/22  0.667531  0.859964  0.957413  1.000000

산술연산 - 리스트, 배열 , numpy라이브러리, pandas라이브러리

In [ ]:
#리스트 연산하기

In [139]:
a=[1,2,3,4,5]
a=a+3

TypeError: ignored

In [140]:
a*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
#넘파이 배열 사용하기

In [143]:
import numpy as np

In [155]:
b=np.array([1,2,3,4,5]) # np.array : numpy 배열 사용가능
b

array([1, 2, 3, 4, 5])

In [156]:
#b배열 모든 원소에 3더하기

In [157]:
b+3

array([4, 5, 6, 7, 8])

In [152]:
#b배열 모든 원소에 3곱하기

In [153]:
b*3

array([ 3,  6,  9, 12, 15])

In [154]:
#np.arange()함수로 6부터 10까지의 c배열 만들기

In [158]:
c=np.arange(6,11)
c

array([ 6,  7,  8,  9, 10])

In [ ]:
#2차원 배열 만들기

In [164]:
d=np.array([[1,2,3,4,5],[6,7,8,9, 10]])
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [165]:
#d배열 모양 확인하기

In [166]:
d.shape

(2, 5)

In [167]:
#배열 b,c 더하기 함수 add

In [168]:
np.add(b,c)

array([ 7,  9, 11, 13, 15])

In [ ]:
#배열 b,c 빼기함수 subtract

In [169]:
np.subtract(b,c)

array([-5, -5, -5, -5, -5])

In [170]:
#배열 b,c 곱하기함수 multiply

In [171]:
np.multiply(b,c)

array([ 6, 14, 24, 36, 50])

In [172]:
#배열 b,c 나누기함수 divide

In [173]:
np.divide(b,c)

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [174]:
#numpy 같은 위치의 원소의 계산함.

스스로해보기2

In [ ]:
import numpy as np

In [175]:
b=np.array([10,20,30,40,50])
b

array([10, 20, 30, 40, 50])

In [ ]:
#b배열 모든 원소에 3곱하기

In [ ]:
b*3

In [ ]:
#np.arange()함수로 1부터 5까지의 c배열 만들기

In [180]:
c = np.arange(1,6)
c

array([1, 2, 3, 4, 5])

In [ ]:
#배열 c,b 더하기 함수 add

In [181]:
np.add(b,c)

array([11, 22, 33, 44, 55])

In [ ]:
#배열 c,b 빼기함수 subtract

In [182]:
np.subtract(c,b)

array([ -9, -18, -27, -36, -45])

In [ ]:
#배열 b,c 곱하기함수 multiply

In [183]:
np.multiply(b,c)

array([ 10,  40,  90, 160, 250])

In [ ]:
#배열 b,c 나누기함수 divide

In [184]:
np.divide(b,c)

array([10., 10., 10., 10., 10.])

판다스 산술연산

In [ ]:
#시리즈vs숫자 연산

In [185]:
sr1=pd.Series({'a':1,'b':2,'c':3}) #시리즈1
sr1

a    1
b    2
c    3
dtype: int64

In [186]:
sr2=pd.Series({'a':4,'b':5,'c':6}) #시리즈1
sr2

a    4
b    5
c    6
dtype: int64

In [ ]:
#sr1에 5 더하기

In [187]:
sr1+5

a    6
b    7
c    8
dtype: int64

In [ ]:
#시리즈vs시리즈 연산 합구하기

In [188]:
sr1+sr2

a    5
b    7
c    9
dtype: int64

In [ ]:
#NaN이 있는 시리즈 연산

In [ ]:
import numpy as np
sr3=pd.Series({'a':np.nan,'b':1,'c':1}) 
sr3

In [ ]:
#sr2 와 sr3 데이터 합하기

In [ ]:
sr2+sr3

In [ ]:
#데이터 프레임 vs 숫자

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]}, index = ['one','two','three'])
df1

a  b  c
one    1  4  7
two    2  5  8
three  3  6  9

In [189]:
import pandas as pd
df2 = pd.DataFrame({'a':[3,2,1],'b':[6,5,4],'c':[9,8,7]}, index = ['one','two','three'])
df2

a  b  c
one    3  6  9
two    2  5  8
three  1  4  7

In [ ]:
#df1에서 1 빼기

In [ ]:
df-1

In [ ]:
#데이터프레임vs데이터프레임

In [ ]:
#데이터 프레임 간 데이터 합하기

In [ ]:
df1+df2

In [ ]:
#Nan이 있는 데이터 프레임 연산

In [190]:
import pandas as pd
df3 = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'d':[7,8,9]}, index = ['one','two','three'])
df3

a  b  d
one    1  4  7
two    2  5  8
three  3  6  9

In [ ]:
#df2와 df3 의 합

In [ ]:
df2+df3

In [ ]:
#df3의 a+b 값을 e컬럼을 만들어 df3에 추가하기

In [191]:
df3['e']=df3['a']+df3['b']
df3

a  b  d  e
one    1  4  7  5
two    2  5  8  7
three  3  6  9  9

스스로해보기

In [ ]:
#시리즈vs숫자 연산

In [192]:
lib1=pd.Series({'제주':50,'서울':100,'부산':90}) #도서관의 수
lib1

제주     50
서울    100
부산     90
dtype: int64

In [193]:
lib2=pd.Series({'제주':2,'서울':10,'부산':7}) #1년뒤 추가된 도서관의 수
lib2

제주     2
서울    10
부산     7
dtype: int64

In [ ]:
#제주, 서울, 부산 도서관의 비율(lib1/전체도서관의 수)

In [ ]:
#lib1데이터와 lib2데이터 합구하기

In [194]:
lib2 + lib1

제주     52
서울    110
부산     97
dtype: int64

In [ ]:
#NaN이 있는 시리즈 연산

In [195]:
lib3=pd.Series({'제주':np.nan,'서울':1,'부산':2}) #2년뒤 추가된 도서관의 수
lib3

제주    NaN
서울    1.0
부산    2.0
dtype: float64

In [ ]:
#lib2와 lib3데이터 합하기, 결과확인하기

In [ ]:
#데이터프레임vs숫자

In [196]:
import pandas as pd
exam_data={'수학':[90,80,70],'영어':[98,85,95],'음악':[85,95,100],'체육':[100,90,90]}
df1 = pd.DataFrame(exam_data, index = ['서준','우현','인아'])
df1

수학  영어   음악   체육
서준  90  98   85  100
우현  80  85   95   90
인아  70  95  100   90

In [197]:
import pandas as pd
exam_data={'수학':[70,70,70],'영어':[10,20,40],'음악':[50,55,100],'체육':[70,80,10]}
df2 = pd.DataFrame(exam_data, index = ['서준','우현','인아'])
df2

수학  영어   음악  체육
서준  70  10   50  70
우현  70  20   55  80
인아  70  40  100  10

In [ ]:
#df1의 모든 점수에서 -5

In [198]:
df1 -5

수학  영어  음악  체육
서준  85  93  80  95
우현  75  80  90  85
인아  65  90  95  85

In [ ]:
#df1 과 df2 데이터 합구하기

In [199]:
df1 + df2 

수학   영어   음악   체육
서준  160  108  135  170
우현  150  105  150  170
인아  140  135  200  100

In [ ]:
#1차 시험점수, 2차 시험점수 평균 구하기

In [200]:
(df1 + df2) /2

수학    영어     음악    체육
서준  80.0  54.0   67.5  85.0
우현  75.0  52.5   75.0  85.0
인아  70.0  67.5  100.0  50.0

In [ ]:
#NaN이 있는 데이터프레임 연산

In [201]:
#Nan이 있는 df3 생성
import pandas as pd
exam_data={'국어':[10,70,60],'수학':[70,70,70],'영어':[10,20,40],'음악':[50,55,100],'체육':[70,80,10]}
df3 = pd.DataFrame(exam_data, index = ['서준','우현','인아'])
df3

국어  수학  영어   음악  체육
서준  10  70  10   50  70
우현  70  70  20   55  80
인아  60  70  40  100  10

In [ ]:
#df2와 df3 합하여 결과 확인

In [ ]:
#df3의 수학+영어 합 데이터를 df3['수영']컬럼을 만들어 추가하기

In [ ]:
df['수영'] = df3['']

<스스로 해보기 프로젝트>

제주 인구데이터 처리하기
'2019제주인구수 데이터에서 총 인구수가 많은 동네와 그 인구수를 구해주세요~'

In [ ]:
#판다스 라이브러리 사용하기

In [ ]:
import pandas as pd

In [ ]:
#엑셀 파일 불러오기

In [220]:
df=pd.read_excel('/content/제주인구수.xlsx')
df

구 분  합 계 Unnamed: 2 Unnamed: 3     내국인 Unnamed: 5   외국인 Unnamed: 7
0     NaN    계          남          여       남          여     남          여
1   제 주 시  NaN        NaN        NaN  245533     243872  9123       7422
2   한 림 읍  NaN        NaN        NaN   11011      10354  2383       1332
3   애 월 읍  NaN        NaN        NaN   18718      17515   571        541
4   구 좌 읍  NaN        NaN        NaN    8014       7575   440        203
5   조 천 읍  NaN        NaN        NaN   12666      12004   374        269
6   한 경 면  NaN        NaN        NaN    4552       4485   261        107
7   추 자 면  NaN        NaN        NaN     941        792   311         13
8   우 도 면  NaN        NaN        NaN     974        888    19         11
9   일도 1동  NaN        NaN        NaN    1423       1301    43         42
10  일도 2동  NaN        NaN        NaN   16565      17118   102        213
11  이도 1동  NaN        NaN        NaN    3773       3876    56         91
12  이도 2동  NaN        NaN        NaN   24554      25410   305        386
13  삼도 1동  NaN        NaN        NaN    6788       7066    66         85
14  삼도 2동  NaN        NaN        NaN    4254       3920   160         99
15  용담 1동  NaN        NaN        NaN    3714       3511    41         49
16  용담 2동  NaN        NaN        NaN    7580       7494    77        177
17  건 입 동  NaN        NaN        NaN    4774       4537   163         97
18  화 북 동  NaN        NaN        NaN   12413      12442   226        190
19  삼 양 동  NaN        NaN        NaN   12933      12769   101        162
20  봉 개 동  NaN        NaN        NaN    2740       2530    42         51
21  아 라 동  NaN        NaN        NaN   17352      17454   615        603
22  오 라 동  NaN        NaN        NaN    7741       7593   122        132
23    연 동  NaN        NaN        NaN   20376      21137  1062       1133
24  노 형 동  NaN        NaN        NaN   26628      27594  1295       1094
25  외 도 동  NaN        NaN        NaN   11002      10799   125        182
26  이 호 동  NaN        NaN        NaN    2374       2195    95        100
27  도 두 동  NaN        NaN        NaN    1673       1513    68         60

In [ ]:
#컬럼 이름 바꾸기 ['동','계','계(남)','계(여)','내(남)','내(여)','외(남)','외(여)']

In [221]:
df.columns = ['동', '계', '계(남)', '계(여)', '내(남)', '내(여)', '외(남)', '외(여)']
df

동    계 계(남) 계(여)    내(남)    내(여)  외(남)  외(여)
0     NaN    계    남    여       남       여     남     여
1   제 주 시  NaN  NaN  NaN  245533  243872  9123  7422
2   한 림 읍  NaN  NaN  NaN   11011   10354  2383  1332
3   애 월 읍  NaN  NaN  NaN   18718   17515   571   541
4   구 좌 읍  NaN  NaN  NaN    8014    7575   440   203
5   조 천 읍  NaN  NaN  NaN   12666   12004   374   269
6   한 경 면  NaN  NaN  NaN    4552    4485   261   107
7   추 자 면  NaN  NaN  NaN     941     792   311    13
8   우 도 면  NaN  NaN  NaN     974     888    19    11
9   일도 1동  NaN  NaN  NaN    1423    1301    43    42
10  일도 2동  NaN  NaN  NaN   16565   17118   102   213
11  이도 1동  NaN  NaN  NaN    3773    3876    56    91
12  이도 2동  NaN  NaN  NaN   24554   25410   305   386
13  삼도 1동  NaN  NaN  NaN    6788    7066    66    85
14  삼도 2동  NaN  NaN  NaN    4254    3920   160    99
15  용담 1동  NaN  NaN  NaN    3714    3511    41    49
16  용담 2동  NaN  NaN  NaN    7580    7494    77   177
17  건 입 동  NaN  NaN  NaN    4774    4537   163    97
18  화 북 동  NaN  NaN  NaN   12413   12442   226   190
19  삼 양 동  NaN  NaN  NaN   12933   12769   101   162
20  봉 개 동  NaN  NaN  NaN    2740    2530    42    51
21  아 라 동  NaN  NaN  NaN   17352   17454   615   603
22  오 라 동  NaN  NaN  NaN    7741    7593   122   132
23    연 동  NaN  NaN  NaN   20376   21137  1062  1133
24  노 형 동  NaN  NaN  NaN   26628   27594  1295  1094
25  외 도 동  NaN  NaN  NaN   11002   10799   125   182
26  이 호 동  NaN  NaN  NaN    2374    2195    95   100
27  도 두 동  NaN  NaN  NaN    1673    1513    68    60

In [ ]:
#데이터 살펴보기

In [ ]:
#계(남)데이터 채우기

In [206]:
df['계(남)'] = -1
df['계(여)'] = -1
df['계'] = -1
df

동  계  계(남)  계(여)    내(남)    내(여)  외(남)  외(여)
0     NaN -1    -1    -1       남       여     남     여
1   제 주 시 -1    -1    -1  245533  243872  9123  7422
2   한 림 읍 -1    -1    -1   11011   10354  2383  1332
3   애 월 읍 -1    -1    -1   18718   17515   571   541
4   구 좌 읍 -1    -1    -1    8014    7575   440   203
5   조 천 읍 -1    -1    -1   12666   12004   374   269
6   한 경 면 -1    -1    -1    4552    4485   261   107
7   추 자 면 -1    -1    -1     941     792   311    13
8   우 도 면 -1    -1    -1     974     888    19    11
9   일도 1동 -1    -1    -1    1423    1301    43    42
10  일도 2동 -1    -1    -1   16565   17118   102   213
11  이도 1동 -1    -1    -1    3773    3876    56    91
12  이도 2동 -1    -1    -1   24554   25410   305   386
13  삼도 1동 -1    -1    -1    6788    7066    66    85
14  삼도 2동 -1    -1    -1    4254    3920   160    99
15  용담 1동 -1    -1    -1    3714    3511    41    49
16  용담 2동 -1    -1    -1    7580    7494    77   177
17  건 입 동 -1    -1    -1    4774    4537   163    97
18  화 북 동 -1    -1    -1   12413   12442   226   190
19  삼 양 동 -1    -1    -1   12933   12769   101   162
20  봉 개 동 -1    -1    -1    2740    2530    42    51
21  아 라 동 -1    -1    -1   17352   17454   615   603
22  오 라 동 -1    -1    -1    7741    7593   122   132
23    연 동 -1    -1    -1   20376   21137  1062  1133
24  노 형 동 -1    -1    -1   26628   27594  1295  1094
25  외 도 동 -1    -1    -1   11002   10799   125   182
26  이 호 동 -1    -1    -1    2374    2195    95   100
27  도 두 동 -1    -1    -1    1673    1513    68    60

In [ ]:
#계(여)데이터 채우기

In [ ]:
#계 데이터 채우기

In [ ]:
#인덱스를 동으로 변경하기

In [222]:
df.index = df['동']
df

동    계 계(남) 계(여)    내(남)    내(여)  외(남)  외(여)
동                                                      
NaN      NaN    계    남    여       남       여     남     여
제 주 시  제 주 시  NaN  NaN  NaN  245533  243872  9123  7422
한 림 읍  한 림 읍  NaN  NaN  NaN   11011   10354  2383  1332
애 월 읍  애 월 읍  NaN  NaN  NaN   18718   17515   571   541
구 좌 읍  구 좌 읍  NaN  NaN  NaN    8014    7575   440   203
조 천 읍  조 천 읍  NaN  NaN  NaN   12666   12004   374   269
한 경 면  한 경 면  NaN  NaN  NaN    4552    4485   261   107
추 자 면  추 자 면  NaN  NaN  NaN     941     792   311    13
우 도 면  우 도 면  NaN  NaN  NaN     974     888    19    11
일도 1동  일도 1동  NaN  NaN  NaN    1423    1301    43    42
일도 2동  일도 2동  NaN  NaN  NaN   16565   17118   102   213
이도 1동  이도 1동  NaN  NaN  NaN    3773    3876    56    91
이도 2동  이도 2동  NaN  NaN  NaN   24554   25410   305   386
삼도 1동  삼도 1동  NaN  NaN  NaN    6788    7066    66    85
삼도 2동  삼도 2동  NaN  NaN  NaN    4254    3920   160    99
용담 1동  용담 1동  NaN  NaN  NaN    3714    3511    41    49
용담 2동  용담 2동  NaN  NaN  NaN    7580    7494    77   177
건 입 동  건 입 동  NaN  NaN  NaN    4774    4537   163    97
화 북 동  화 북 동  NaN  NaN  NaN   12413   12442   226   190
삼 양 동  삼 양 동  NaN  NaN  NaN   12933   12769   101   162
봉 개 동  봉 개 동  NaN  NaN  NaN    2740    2530    42    51
아 라 동  아 라 동  NaN  NaN  NaN   17352   17454   615   603
오 라 동  오 라 동  NaN  NaN  NaN    7741    7593   122   132
연 동      연 동  NaN  NaN  NaN   20376   21137  1062  1133
노 형 동  노 형 동  NaN  NaN  NaN   26628   27594  1295  1094
외 도 동  외 도 동  NaN  NaN  NaN   11002   10799   125   182
이 호 동  이 호 동  NaN  NaN  NaN    2374    2195    95   100
도 두 동  도 두 동  NaN  NaN  NaN    1673    1513    68    60

In [ ]:
#df1데이터에서 '제 주 시' 인덱스 삭제하여 df2에 저장

In [ ]:
#df1데이터를 가나다 순 정렬하여 df3에 저장

In [208]:
df3 = df.sort_index()
df3

동  계  계(남)  계(여)    내(남)    내(여)  외(남)  외(여)
동                                                      
건 입 동  건 입 동 -1    -1    -1    4774    4537   163    97
구 좌 읍  구 좌 읍 -1    -1    -1    8014    7575   440   203
노 형 동  노 형 동 -1    -1    -1   26628   27594  1295  1094
도 두 동  도 두 동 -1    -1    -1    1673    1513    68    60
봉 개 동  봉 개 동 -1    -1    -1    2740    2530    42    51
삼 양 동  삼 양 동 -1    -1    -1   12933   12769   101   162
삼도 1동  삼도 1동 -1    -1    -1    6788    7066    66    85
삼도 2동  삼도 2동 -1    -1    -1    4254    3920   160    99
아 라 동  아 라 동 -1    -1    -1   17352   17454   615   603
애 월 읍  애 월 읍 -1    -1    -1   18718   17515   571   541
연 동      연 동 -1    -1    -1   20376   21137  1062  1133
오 라 동  오 라 동 -1    -1    -1    7741    7593   122   132
외 도 동  외 도 동 -1    -1    -1   11002   10799   125   182
용담 1동  용담 1동 -1    -1    -1    3714    3511    41    49
용담 2동  용담 2동 -1    -1    -1    7580    7494    77   177
우 도 면  우 도 면 -1    -1    -1     974     888    19    11
이 호 동  이 호 동 -1    -1    -1    2374    2195    95   100
이도 1동  이도 1동 -1    -1    -1    3773    3876    56    91
이도 2동  이도 2동 -1    -1    -1   24554   25410   305   386
일도 1동  일도 1동 -1    -1    -1    1423    1301    43    42
일도 2동  일도 2동 -1    -1    -1   16565   17118   102   213
제 주 시  제 주 시 -1    -1    -1  245533  243872  9123  7422
조 천 읍  조 천 읍 -1    -1    -1   12666   12004   374   269
추 자 면  추 자 면 -1    -1    -1     941     792   311    13
한 경 면  한 경 면 -1    -1    -1    4552    4485   261   107
한 림 읍  한 림 읍 -1    -1    -1   11011   10354  2383  1332
화 북 동  화 북 동 -1    -1    -1   12413   12442   226   190
NaN      NaN -1    -1    -1       남       여     남     여

In [223]:
#df2에서 전체 인구가 가장 많은 동 을 정렬하고 df4에 저장
df.drop([df.index[0]], axis = 0)

동    계 계(남) 계(여)    내(남)    내(여)  외(남)  외(여)
동                                                      
제 주 시  제 주 시  NaN  NaN  NaN  245533  243872  9123  7422
한 림 읍  한 림 읍  NaN  NaN  NaN   11011   10354  2383  1332
애 월 읍  애 월 읍  NaN  NaN  NaN   18718   17515   571   541
구 좌 읍  구 좌 읍  NaN  NaN  NaN    8014    7575   440   203
조 천 읍  조 천 읍  NaN  NaN  NaN   12666   12004   374   269
한 경 면  한 경 면  NaN  NaN  NaN    4552    4485   261   107
추 자 면  추 자 면  NaN  NaN  NaN     941     792   311    13
우 도 면  우 도 면  NaN  NaN  NaN     974     888    19    11
일도 1동  일도 1동  NaN  NaN  NaN    1423    1301    43    42
일도 2동  일도 2동  NaN  NaN  NaN   16565   17118   102   213
이도 1동  이도 1동  NaN  NaN  NaN    3773    3876    56    91
이도 2동  이도 2동  NaN  NaN  NaN   24554   25410   305   386
삼도 1동  삼도 1동  NaN  NaN  NaN    6788    7066    66    85
삼도 2동  삼도 2동  NaN  NaN  NaN    4254    3920   160    99
용담 1동  용담 1동  NaN  NaN  NaN    3714    3511    41    49
용담 2동  용담 2동  NaN  NaN  NaN    7580    7494    77   177
건 입 동  건 입 동  NaN  NaN  NaN    4774    4537   163    97
화 북 동  화 북 동  NaN  NaN  NaN   12413   12442   226   190
삼 양 동  삼 양 동  NaN  NaN  NaN   12933   12769   101   162
봉 개 동  봉 개 동  NaN  NaN  NaN    2740    2530    42    51
아 라 동  아 라 동  NaN  NaN  NaN   17352   17454   615   603
오 라 동  오 라 동  NaN  NaN  NaN    7741    7593   122   132
연 동      연 동  NaN  NaN  NaN   20376   21137  1062  1133
노 형 동  노 형 동  NaN  NaN  NaN   26628   27594  1295  1094
외 도 동  외 도 동  NaN  NaN  NaN   11002   10799   125   182
이 호 동  이 호 동  NaN  NaN  NaN    2374    2195    95   100
도 두 동  도 두 동  NaN  NaN  NaN    1673    1513    68    60

In [227]:
#df['인구수 총합'] = None

for i in range(28):
    df.iloc[i]['인구수 총합'] = df['내(남)'] + df['내(여)'] + df['외(남)'] + df['외(여)']
df

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


동    계 계(남) 계(여)    내(남)    내(여)  외(남)  외(여) 인구수 총합  인구수총합
동                                                                    
NaN      NaN    계    남    여       남       여     남     여   None    NaN
제 주 시  제 주 시  NaN  NaN  NaN  245533  243872  9123  7422   None    NaN
한 림 읍  한 림 읍  NaN  NaN  NaN   11011   10354  2383  1332   None    NaN
애 월 읍  애 월 읍  NaN  NaN  NaN   18718   17515   571   541   None    NaN
구 좌 읍  구 좌 읍  NaN  NaN  NaN    8014    7575   440   203   None    NaN
조 천 읍  조 천 읍  NaN  NaN  NaN   12666   12004   374   269   None    NaN
한 경 면  한 경 면  NaN  NaN  NaN    4552    4485   261   107   None    NaN
추 자 면  추 자 면  NaN  NaN  NaN     941     792   311    13   None    NaN
우 도 면  우 도 면  NaN  NaN  NaN     974     888    19    11   None    NaN
일도 1동  일도 1동  NaN  NaN  NaN    1423    1301    43    42   None    NaN
일도 2동  일도 2동  NaN  NaN  NaN   16565   17118   102   213   None    NaN
이도 1동  이도 1동  NaN  NaN  NaN    3773    3876    56    91   None    NaN
이도 2동  이도 2동  NaN  NaN  NaN   24554   25410   305   386   None    NaN
삼도 1동  삼도 1동  NaN  NaN  NaN    6788    7066    66    85   None    NaN
삼도 2동  삼도 2동  NaN  NaN  NaN    4254    3920   160    99   None    NaN
용담 1동  용담 1동  NaN  NaN  NaN    3714    3511    41    49   None    NaN
용담 2동  용담 2동  NaN  NaN  NaN    7580    7494    77   177   None    NaN
건 입 동  건 입 동  NaN  NaN  NaN    4774    4537   163    97   None    NaN
화 북 동  화 북 동  NaN  NaN  NaN   12413   12442   226   190   None    NaN
삼 양 동  삼 양 동  NaN  NaN  NaN   12933   12769   101   162   None    NaN
봉 개 동  봉 개 동  NaN  NaN  NaN    2740    2530    42    51   None    NaN
아 라 동  아 라 동  NaN  NaN  NaN   17352   17454   615   603   None    NaN
오 라 동  오 라 동  NaN  NaN  NaN    7741    7593   122   132   None    NaN
연 동      연 동  NaN  NaN  NaN   20376   21137  1062  1133   None    NaN
노 형 동  노 형 동  NaN  NaN  NaN   26628   27594  1295  1094   None    NaN
외 도 동  외 도 동  NaN  NaN  NaN   11002   10799   125   182   None    NaN
이 호 동  이 호 동  NaN  NaN  NaN    2374    2195    95   100   None    NaN
도 두 동  도 두 동  NaN  NaN  NaN    1673    1513    68    60   None    NaN

In [ ]:
#가장 인구가 많은 동 5개 뽑아 df5에 저장하기

In [ ]:
#max_dong에 인구가 많은 동 저장, max_pop에 총 인구수 저장

In [ ]:
#가장 인구가 많은 동은 ~ 동이고, 총 ~ 이 거주하고 있다. 출력

In [ ]:
print('가장 인구가 많은 동은',max_dong,'이고, 총',max_pop,'명이 거주하고 있다.')